firma-mvc/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using firma_mvc;
using firma_mvc.Data;

namespace firma_mvc.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Company.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InvoiceIssuerName,InvoiceIssueCity,Id,NIP,FullName,Name,CountryCode,Voivodeship,County,Community,City,Street,BuldingNo,PostalCode,PostOffice,Email,Phone")] Company company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InvoiceIssuerName,InvoiceIssueCity,Id,NIP,FullName,Name,CountryCode,Voivodeship,County,Community,City,Street,BuldingNo,PostalCode,PostOffice,Email,Phone,REGON,BankName,BankAccountNumber,Website")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(HomeController.Settings));
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPartial(int id, [Bind("InvoiceIssuerName,InvoiceIssueCity,Id,NIP,FullName,Name,CountryCode,Voivodeship,County,Community,City,Street,BuldingNo,PostalCode,PostOffice,Email,Phone,REGON,BankName,BankAccountNumber,Website")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Settings", "Home", new { info = "Zmiany zapisane" });
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Company.FindAsync(id);
            _context.Company.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _context.Company.Any(e => e.Id == id);
        }
    }
}

firma-mvc/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using firma_mvc;
using firma_mvc.Data;

namespace firma_mvc.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index(string searchQuery)
        {
            var applicationDbContext = _context.Item.Include(i => i.UnitOfMeasure).Include(i => i.VAT);

            if (!String.IsNullOrEmpty (searchQuery))
            {
                var searchResult = applicationDbContext.Where (p => p.Name.Contains (searchQuery));
                return View (await searchResult.ToListAsync ());
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(i => i.UnitOfMeasure)
                .Include(i => i.VAT)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["UnitOfMeasureId"] = new SelectList(_context.UnitOfMeasure, "Id", "ShortName");
            ViewData["VATId"] = new SelectList(_context.VAT, "Id", "Value");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,UnitOfMeasureId,VATId,Price")] Item item)
        {
            if (ModelState.IsValid)
            {
                item.Price = Tools.decimalRound(item.Price);
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UnitOfMeasureId"] = new SelectList(_context.UnitOfMeasure, "Id", "ShortName", item.UnitOfMeasureId);
            ViewData["VATId"] = new SelectList(_context.VAT, "Id", "Value", item.VATId);
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.SingleOrDefaultAsync((System.Linq.Expressions.Expression<Func<Item, bool>>)(m => m.Id == id));
            if (item == null)
            {
                return NotFound();
            }
            ViewData["UnitOfMeasureId"] = new SelectList(_context.UnitOfMeasure, "Id", "Id", item.UnitOfMeasureId);
            ViewData["VATId"] = new SelectList(_context.VAT, "Id", "Id", item.VATId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,UnitOfMeasureId,VATId,Price")] Item item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UnitOfMeasureId"] = new SelectList(_context.UnitOfMeasure, "Id", "Id", item.UnitOfMeasureId);
            ViewData["VATId"] = new SelectList(_context.VAT, "Id", "Id", item.VATId);
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(i => i.UnitOfMeasure)
                .Include(i => i.VAT)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Item.SingleOrDefaultAsync((System.Linq.Expressions.Expression<Func<Item, bool>>)(m => m.Id == id));
            _context.Item.Remove((Item)item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any((System.Linq.Expressions.Expression<Func<Item, bool>>)(e => e.Id == id));
        }

        // GET: Items/GetItem/5
        public async Task<IActionResult> GetItem(int? id)
        {
            var item = await _context.Item
                .Include(i => i.UnitOfMeasure)
                .Include(i => i.VAT)
                .SingleOrDefaultAsync(m => m.Id == id);
            
            return Json(item);
        }
    }
}

firma-mvc/Controllers/VATsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using firma_mvc;
using firma_mvc.Data;

namespace firma_mvc.Controllers
{
    public class VATsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VATsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: VATs
        public async Task<IActionResult> Index()
        {
            return View(await _context.VAT.ToListAsync());
        }

        // GET: VATs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vAT = await _context.VAT
                .SingleOrDefaultAsync(m => m.Id == id);
            if (vAT == null)
            {
                return NotFound();
            }

            return View(vAT);
        }

        // GET: VATs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VATs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Value")] VAT vAT)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vAT);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vAT);
        }

        // GET: VATs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vAT = await _context.VAT.SingleOrDefaultAsync(m => m.Id == id);
            if (vAT == null)
            {
                return NotFound();
            }
            return View(vAT);
        }

        // POST: VATs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Value")] VAT vAT)
        {
            if (id != vAT.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vAT);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VATExists(vAT.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vAT);
        }

        // GET: VATs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vAT = await _context.VAT
                .SingleOrDefaultAsync(m => m.Id == id);
            if (vAT == null)
            {
                return NotFound();
            }

            return View(vAT);
        }

        // POST: VATs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vAT = await _context.VAT.SingleOrDefaultAsync(m => m.Id == id);
            _context.VAT.Remove(vAT);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VATExists(int id)
        {
            return _context.VAT.Any(e => e.Id == id);
        }
    }
}

firma-mvc/Views/Shared/Sidebar.cshtml
@{
    string controller = ViewContext.RouteData.Values["Controller"].ToString();    
}
<br />

<div class="accordion" id="accordionExample">

    <div class="card">
        <a class="a-custom" href="~/Invoices">
            <div class="card-header" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                <h6 class="mb-0">
                    Faktury
                </h6>
            </div>
            </a>
            @if(controller=="Invoices")
            {
                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                                    <div>
                    @await Html.PartialAsync("SidebarInvoices")
                </div>
            </div>
            }
            else
            {
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                                    <div>
                    @await Html.PartialAsync("SidebarInvoices")
                </div>
            </div>
            }
    </div>

    <div class="card">
        <a class="a-custom" href="~/TaxBooks">
            <div class="card-header" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <h6 class="mb-0">
                    KPiR
                </h6>
            </div>
            </a>
    </div>

    <div class="card">
        <a class="a-custom" href="#">
            <div class="card-header" id="headingThree" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                <h6 class="mb-0">
                    Rejestr VAT
                </h6>
            </div>
            </a>
            @if(controller=="VATRegisterSells" || controller=="VATRegisterBuys")
            {           
            <div id="collapseThree" class="collapse show" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div>
                    @await Html.PartialAsync("SidebarVATregister")
                </div>
            </div>
            }
            else
            {
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                <div>
                    @await Html.PartialAsync("SidebarVATregister")
                </div>
            </div>
            }
</div>

    <div class="card">
        <a class="a-custom" href="~/Contractors">
            <div class="card-header" id="headingFour" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                <h6 class="mb-0">
                    Kontrahenci
                </h6>
            </div>
            </a>
    </div>

    <div class="card">
        <a class="a-custom" href="~/Items">
            <div class="card-header" id="headingFive" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                <h6 class="mb-0">
                    Towary i usługi
                </h6>
            </div>
            </a>
    </div>

    <div class="card">
        <a class="a-custom" href="#">
            <div class="card-header" id="headingSix" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
                <h6 class="mb-0">
                    Podatki
                </h6>
            </div>
            </a>
            @if(controller=="VAT7" || controller=="IncomeTaxes")
            {
            <div id="collapseSix" class="collapse show" aria-labelledby="headingSix" data-parent="#accordionExample">
                <div>
                    @await Html.PartialAsync("SidebarTax")
                </div>
            </div>
            }
            else
            {
                <div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#accordionExample">
                <div>
                    @await Html.PartialAsync("SidebarTax")
                </div>
            </div>
            }
    </div>

    <div class="card">
        <a class="a-custom" href="~/JPK">
            <div class="card-header" id="headingSeven" data-toggle="collapse" data-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                <h6 class="mb-0">
                    Generator JPK
                </h6>
            </div>
            </a>
    </div>

        <div class="card">
            <a class="a-custom" href="~/FixedAssets">
                <div class="card-header" id="headingEight" data-toggle="collapse" data-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                    <h6 class="mb-0">
                        Środki trwałe
                    </h6>
                </div>
            </a>
        </div>

        <div class="card">
            <a class="a-custom" href="~/Calc">
                <div class="card-header" id="headingNine" data-toggle="collapse" data-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                    <h6 class="mb-0">
                        Kalkulator
                    </h6>
                </div>
            </a>
        </div>

        <div class="card">
            <a class="a-custom" href="~/CarCosts">
                <div class="card-header" id="headingNine" data-toggle="collapse" data-target="#collapseTen" aria-expanded="false" aria-controls="collapseTen">
                    <h6 class="mb-0">
                        Dziennik kosztów utrzymania pojazdu
                    </h6>
                </div>
            </a>
        </div>
    </div>

firma-mvc/Views/Shared/SidebarInvoices.cshtml
 <table class="table table-hover">
        <tbody>
            <tr class="table-light" data-toggle="modal" data-target="#newInvoice"><td><i class="far fa-file"></i> Nowa</td></tr>
            <tr class="table-light" onclick="location.href = '@Url.Action("Index", "InvoiceCorrections")'"><td><i class="far fa-edit"></i> Korekty</td></tr>
            <tr class="table-light"><td><i class="far fa-file-alt"></i> Robocze</td></tr>
            <tr class="table-light"><td><i class="fas fa-th-list"></i> Szablony</td></tr>
        </tbody>
    </table>

<!-- Modal -->
<div class="modal fade" id="newInvoice" tabindex="-1" role="dialog" aria-labelledby="newInvoiceLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="newInvoiceLabel">Nowa faktura</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    @await Html.PartialAsync("../Invoices/CreatePartial", @ViewData["Invoice"])
                </div>
            </div>
        </div>
    </div>
</div>

firma-mvc/Views/Shared/_Layout with side menu.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Computerman Firma</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">
            <img src="~/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            Computerman
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">@Html.ActionLink("Sprzedaż", "Index", "Invoices", null, htmlAttributes: new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Księga", "Index", "TaxBooks", null, htmlAttributes: new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Środki trwałe", "Index", "FixedAssets", null, htmlAttributes: new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Towary i usługi", "Index", "Items", null, htmlAttributes: new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Kontrahenci", "Index", "Contractors", null, htmlAttributes: new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("JPK", "Index", "Contractors", null, htmlAttributes: new { @class = "nav-link" })</li>

                <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown navbar-right">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Rejestr VAT
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @Html.ActionLink("Sprzedaż", "Index", "VATRegisterSells", null, htmlAttributes: new { @class = "dropdown-item" })
                                @Html.ActionLink("Zakupy", "Index", "VATRegisterBuys", null, htmlAttributes: new { @class = "dropdown-item" })
                            </div>
                        </li>
                    </ul>
                </div>

            </ul>

            <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown navbar-right">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Ustawienia
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Statusy faktury", "Index", "InvoiceStatus", null, htmlAttributes: new { @class = "dropdown-item" })
                            @Html.ActionLink("Jednostki miar", "Index", "UnitOfMeasures", null, htmlAttributes: new { @class = "dropdown-item" })
                            @Html.ActionLink("Formy płatności", "Index", "PaymentMethods", null, htmlAttributes: new { @class = "dropdown-item" })
                            @Html.ActionLink("VAT", "Index", "VATs", null, htmlAttributes: new { @class = "dropdown-item" })
                            @Html.ActionLink("Parametry", "Index", "Parameters", null, htmlAttributes: new { @class = "dropdown-item" })
                            @Html.ActionLink("Moja firma", "Index", "Companies", null, htmlAttributes: new { @class = "dropdown-item" })
                        </div>
                    </li>
                </ul>
            </div>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </nav>

    <div class="container-fluid">
            <div class="row">
                <div class="col-2">
                    <p></p>
                    <div class="card bg-primary mb-3">
                        <div class="card-header text-white">
                            Featured
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Cras justo odio</li>
                            <li class="list-group-item">Dapibus ac facilisis in</li>
                            <li class="list-group-item">Vestibulum at eros</li>
                        </ul>
                    </div>
                </div>
                <div class="col-10 body-content">
                    @RenderBody()
                    <hr />
                    <p>&copy; @DateTime.Now.Year - Computerman Firma</p>
                </div>
            </div>
        </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>