firma-mvc/Models/Others/Contractor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Xml.Linq;

namespace firma_mvc
{
    public class Contractor
    {
        public int Id { get; set; }
        public string NIP { get; set; }
        [DisplayName("Pełna nazwa")]
        public string FullName { get; set; }
        [DisplayName("Nazwa skrócona")]
        public string Name { get; set; }
        [DisplayName("Kod kraju")]
        public string CountryCode { get; set; }
        [DisplayName("Województwo")]
        public string Voivodeship { get; set; }
        [DisplayName("Powiat")]
        public string County { get; set; }
        [DisplayName("Gmina")]
        public string Community { get; set; }
        [DisplayName("Miejscowość")]
        public string City { get; set; }
        [DisplayName("Ulica")]
        public string Street { get; set; }
        [DisplayName("Nr budynku")]
        public string BuldingNo { get; set; }
        [DisplayName("Kod pocztowy")]
        public string PostalCode { get; set; }
        [DisplayName("Poczta")]
        public string PostOffice { get; set; }
        [EmailAddress]
        [DisplayName("E-mail")]
        public string Email { get; set; }
        [Phone]
        [DisplayName("Telefon")]
        public string Phone { get; set; }
        public virtual string FullAddress { get { return getFullAddress(); } }

        public Contractor()
        {
        }

        public Contractor(int id)
        {
            Id = id;
        }

        public Contractor(string nip)
        {
            NIP = nip;
        }

        public Contractor(string nip, string name, string countryCode, string voivodeship, string county,
            string community, string city, string street, string buldingNo, string postalCode, string postOffice)
        {
            NIP = nip;
            FullName = name;
            CountryCode = countryCode;
            Voivodeship = voivodeship;
            County = county;
            Community = community;
            City = city;
            Street = street;
            BuldingNo = buldingNo;
            PostalCode = postalCode;
            PostOffice = postOffice;
        }

        string getFullAddress()
        {
            return "ul. " + Street + " " + BuldingNo + ", " + PostalCode + " " + City;
        }

        //public bool add()
        //{
        //    bool success = true;

        //    Database db = new Database();
        //    db.Contractor.Add(this);
        //    db.SaveChanges();

        //    return success;
        //}

        //public Contractor get(int id)
        //{
        //    Database db = new Database();
        //    return db.Contractor.Single(p => p.Id == id);
        //}

        //public Contractor get(string nip)
        //{
        //    Database db = new Database();
        //    return db.Contractor.Single(p => p.NIP == nip);
        //}

        //public List<Contractor> getAll()
        //{
        //    Database db = new Database();
        //    List<Contractor> contractors = db.Contractor.Select(p => p).ToList();
        //    return contractors;
        //}

        public void printAll(List<Contractor> contractors)
        {
            int i = 1;
            foreach (Contractor c in contractors)
            {
                Console.WriteLine(i + "\t" + c.FullName + "\t" + c.NIP + "\t" + c.CountryCode + "\t" + c.PostalCode + "\t" +
                                  c.City + "\t" + c.Street + "\t" + c.BuldingNo);
                i++;
            }
        }



        //public bool add()
        //{
        //    string path = "contractors.xml";

        //    if (!File.Exists(path))
        //    {
        //        XDocument newDoc = new XDocument();
        //        XElement newRoot = new XElement("Contractors");
        //        newDoc.Add(newRoot);
        //        newDoc.Save(path);
        //    }

        //    XElement contractor = new XElement("Contractor");
        //    contractor.Add(new XAttribute("NIP", NIP));
        //    contractor.Add(new XAttribute("FullName", FullName));
        //    contractor.Add(new XAttribute("CountryCode", CountryCode));
        //    contractor.Add(new XAttribute("Voivodeship", Voivodeship));
        //    contractor.Add(new XAttribute("County", County));
        //    contractor.Add(new XAttribute("Community", Community));
        //    contractor.Add(new XAttribute("City", City));
        //    contractor.Add(new XAttribute("Street", Street));
        //    contractor.Add(new XAttribute("BuldingNo", BuldingNo));
        //    contractor.Add(new XAttribute("PostalCode", PostalCode));
        //    contractor.Add(new XAttribute("PostOffice", PostOffice));


        //    XElement root = XElement.Load(path);
        //    root.Add(contractor);
        //    root.Save(path);

        //    return true;
        //}

        //public List<Contractor> getAll()
        //{
        //    string path = "contractors.xml";
        //    List<Contractor> list = new List<Contractor>();

        //    XDocument doc = XDocument.Load(path);

        //    int i = 1;
        //    foreach (XElement elem in doc.Element("Contractors").Elements("Contractor"))
        //    {
        //        Contractor contractor = get(elem);
        //        list.Add(contractor);
        //        contractor.print(i);
        //        i++;
        //    }

        //    return list;
        //}

        //public Contractor get(XElement contractorElement)
        //{
        //    Contractor contractor = new Contractor();
        //    contractor.FullName = contractorElement.Attribute("FullName").Value;
        //    contractor.NIP = contractorElement.Attribute("NIP").Value;
        //    contractor.CountryCode = contractorElement.Attribute("CountryCode").Value;
        //    contractor.Voivodeship = contractorElement.Attribute("Voivodeship").Value;
        //    contractor.County = contractorElement.Attribute("County").Value;
        //    contractor.Community = contractorElement.Attribute("Community").Value;
        //    contractor.City = contractorElement.Attribute("City").Value;
        //    contractor.Street = contractorElement.Attribute("Street").Value;
        //    contractor.BuldingNo = contractorElement.Attribute("BuldingNo").Value;
        //    contractor.PostalCode = contractorElement.Attribute("PostalCode").Value;
        //    contractor.PostOffice = contractorElement.Attribute("PostOffice").Value;

        //    return contractor;
        //}

        //void print(int i)
        //{
        //    Console.WriteLine(i + "\t" + FullName + "\t" + NIP + "\t" + CountryCode + "\t" + PostalCode + "\t" +
        //                      City + "\t" + Street + "\t" + BuldingNo);
        //}

    }
}

firma-mvc/Controllers/ContractorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using firma_mvc;
using firma_mvc.Data;

namespace firma_mvc.Controllers
{
    public class ContractorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContractorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contractors
        public async Task<IActionResult> Index(string searchQuery)
        {
            var applicationDbContext = _context.Contractor;

            if (!String.IsNullOrEmpty(searchQuery))
            {
                var searchResult = applicationDbContext.Where(p => p.Name.Contains(searchQuery) || p.NIP.Contains(searchQuery));
                return View(await searchResult.ToListAsync());
            }

            //             FixedAssets fixedAssets = new FixedAssets();
            // fixedAssets.DateOfBuy = DateTime.Now.Date;
            // fixedAssets.DateOfUseStart = DateTime.Now.Date;
            // fixedAssets.Identfier = fixedAssets.getNumber(_context);
            // ViewData["FixedAssets"] = fixedAssets;

            // Contractor contractor = new Contractor();
            // contractor.Name="test";
            // ViewData["Contractor"]=contractor;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Contractors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contractor = await _context.Contractor
                .SingleOrDefaultAsync(m => m.Id == id);
            if (contractor == null)
            {
                return NotFound();
            }

            return View(contractor);
        }

        // GET: Contractors/Create
        public IActionResult Create()
        {
            // List<string> voivodeships = new List<string>() {"kujawsko-pomorskie", "lubuskie", "małopolskie","mazowieckie", "pomorskie", "śląskie", "warmińsko-mazurskie", "wielkopolskie", "zachodniopomorskie"};
            // ViewData["Voivodeships"] = new SelectList(voivodeships);
            return View();
        }

        // POST: Contractors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NIP,FullName,Name,CountryCode,Voivodeship,County,Community,City,Street,BuldingNo,PostalCode,PostOffice,Email,Phone")] Contractor contractor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contractor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { searchQuery = string.Empty });
            }
            return View(contractor);
        }

        // GET: Contractors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contractor = await _context.Contractor.SingleOrDefaultAsync(m => m.Id == id);
            if (contractor == null)
            {
                return NotFound();
            }
            return View(contractor);
        }

        // POST: Contractors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NIP,FullName,Name,CountryCode,Voivodeship,County,Community,City,Street,BuldingNo,PostalCode,PostOffice,Email,Phone")] Contractor contractor)
        {
            if (id != contractor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contractor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractorExists(contractor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contractor);
        }

        // GET: Contractors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contractor = await _context.Contractor
                .SingleOrDefaultAsync(m => m.Id == id);
            if (contractor == null)
            {
                return NotFound();
            }

            return View(contractor);
        }

        // POST: Contractors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contractor = await _context.Contractor.SingleOrDefaultAsync(m => m.Id == id);
            _context.Contractor.Remove(contractor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContractorExists(int id)
        {
            return _context.Contractor.Any(e => e.Id == id);
        }

        // GET: Contractors/SearchContractor
        public async Task<IActionResult> SearchContractor(string query)
        {
            var item = _context.Contractor.Where(p=>p.Name.Contains(query));
            
            return Json(item);
        }
    }
}

firma-mvc/Views/Contractors/Create.cshtml
@model firma_mvc.Contractor

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Contractor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NIP" class="control-label"></label>
                <input asp-for="NIP" class="form-control" />
                <span asp-validation-for="NIP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryCode" class="control-label"></label>
                <input asp-for="CountryCode" class="form-control" />
                <span asp-validation-for="CountryCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voivodeship" class="control-label"></label>
                <input asp-for="Voivodeship" class="form-control" />
                <span asp-validation-for="Voivodeship" class="text-danger"></span>
            </div>
            @*<div class="form-group col-md-6">
                <label asp-for="Voivodeship" class="control-label"></label>
                <select asp-for="Voivodeship" class="form-control custom-select" asp-items="ViewBag.Voivodeships"></select>
            </div>*@
            <div class="form-group">
            <label asp-for="County" class="control-label"></label>
            <input asp-for="County" class="form-control" />
            <span asp-validation-for="County" class="text-danger"></span>
        </div>
            <div class="form-group">
                <label asp-for="Community" class="control-label"></label>
                <input asp-for="Community" class="form-control" />
                <span asp-validation-for="Community" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BuldingNo" class="control-label"></label>
                <input asp-for="BuldingNo" class="form-control" />
                <span asp-validation-for="BuldingNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostOffice" class="control-label"></label>
                <input asp-for="PostOffice" class="form-control" />
                <span asp-validation-for="PostOffice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

firma-mvc/Views/Contractors/CreatePartial.cshtml
@model firma_mvc.Contractor

<div class="row">
    <form asp-action="Create" asp-controller="Contractors">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="row">
            <div class="form-group col-md-4">
                <label asp-for="NIP" class="control-label"></label>
                <input asp-for="NIP" class="form-control" />
                <span asp-validation-for="NIP" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-8">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-9">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="BuldingNo" class="control-label"></label>
                <input asp-for="BuldingNo" class="form-control" />
                <span asp-validation-for="BuldingNo" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-2">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <label asp-for="PostOffice" class="control-label"></label>
                <input asp-for="PostOffice" class="form-control" />
                <span asp-validation-for="PostOffice" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-2">
                <label asp-for="CountryCode" class="control-label"></label>
                <input asp-for="CountryCode" class="form-control" />
                <span asp-validation-for="CountryCode" class="text-danger"></span>
            </div>
            @*<div class="form-group col-md-4">
                    <label asp-for="Voivodeship" class="control-label"></label>
                    <select asp-for="Voivodeship" class="form-control" asp-items="ViewBag.Voivodeships"></select>
                </div>*@
            <div class="form-group col-md-4">
                <label asp-for="Voivodeship" class="control-label"></label>
                <input asp-for="Voivodeship" class="form-control" />
                <span asp-validation-for="Voivodeship" class="text-danger"></span>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="County" class="control-label"></label>
                <input asp-for="County" class="form-control" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="Community" class="control-label"></label>
                <input asp-for="Community" class="form-control" />
                <span asp-validation-for="Community" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="form-group col">
                <label asp-for="Email" class="control-label"></label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group col">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="row col">
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-outline-success" />
            </div>
            <div class="form-group col">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Anuluj</button>
            </div>
        </div>


    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

firma-mvc/Views/Contractors/Delete.cshtml
@model firma_mvc.Contractor

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contractor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NIP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NIP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CountryCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CountryCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Voivodeship)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Voivodeship)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Community)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Community)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BuldingNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BuldingNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostOffice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostOffice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

firma-mvc/Views/Contractors/Index.cshtml
@model IEnumerable<firma_mvc.Contractor>

@{
    ViewData["Title"] = "Index";
}

<p>
    <h2>Kontrahenci</h2>
</p>

<form>
    <div class="form-row align-items-center">
        <div class="my-2">
            <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModal">
                Dodaj
            </button>
        </div>
        <div class="col-sm-3 my-1">
            <input class="form-control" type="text" name="searchQuery" placeholder="NIP lub nazwa kontrahenta" aria-label="Search">
        </div>
        <div class="my-1">
            <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search"></i> Szukaj</button>
        </div>
</form>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Dodaj nowego kontrahenta</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="container-fluid">
                                @* @await Html.PartialAsync("CreatePartial", @ViewData["Contractor"]) *@
                                @await Component.InvokeAsync("ContractorCreate", new Contractor())
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>
                #
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NIP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr class="table-light" onclick="location.href = '@Url.Action("Details", "Contractors",new { id = item.Id})'">
                <td>
                    @i
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NIP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
            </tr>
            i++;
        }
    </tbody>
</table>